alipay:
  # appid
  appId: 
  # 客户私钥
  privateKey: 
  # 支付宝公钥
  publicKey: 
  # 支付宝网关
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  # 回调地址
  notifyUrl: http://localhost:3090/
  # 支付完成后返回的地址
  returnUrl: http://localhost:3090/
  # 签名方式
  signType: RSA2
  # 字符编码格式
  charset: utf-8
  # 格式
  format: json

